name: Modelops deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]

jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v3

    # Install Python and dependencies
    - name: Check Python version
      run: python --version

    - name: Install pip dependencies
      run: pip install -r requirements.txt
      
    # Check dataset URL
    - name: Check dataset URL
      run: |
        if [ -z "${{ github.event.client_payload.dataseturl }}" ]; then
          echo "Error: dataseturl is not set"
          exit 1
        fi

    # Download dataset
    - name: Download dataset
      run: wget -O data/heart_disease.csv ${{ github.event.client_payload.dataseturl }}
    
    - name: Cat dataset
      run: cat data/heart_disease.csv

    # Train model
    - name: Train model
      run: python model/train.py

    # Docker build
    - name: Docker build
      run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.MODEL_NAME }}:${{ github.sha }} .

    - name: Show Docker images
      run: docker images

    # Docker login and push
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Docker push
      run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.MODEL_NAME }}:${{ github.sha }}
