name: Modelops deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ml_ci_cd]

jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Pip install
    - name: Check Python version
      run: python --version

    - name: Install pip dependencies
      run: pip install -r requirements.txt

    # Download Dataset
    - name: download dataset
      run: wget -O data/heart_disease.csv ${{github.event.client_payload.dataseturl}}
    - name: cat dataset
      run: cat data/heart_disease.csv


    # Train model
    - name: Train model
      run: python model/train.py

    # Docker login, docker build
    - name: Docker build
      run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.MODEL_NAME }}:${{ github.sha }} .

    - name: Show Docker images
      run: docker images

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "$DOCKER_USER" --password-stdin 

    - name: Docker push
      run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.MODEL_NAME }}:${{ github.sha }}
